package com.anda.moments.commons;

public class Constant {

	
    /**
     * 超时时间
     */
    public static final int TIMEOUT = 10000;

    private static final int GD_LOG_LEVEL_INFO = 3;

    private static final int GD_LOG_LEVEL_NONE = 0;
    
    public static final String FILE_NAME = "moments";
    //手势密码
    public static final String GESTURE_PWD = "gesture_pwd";
    
    public static final String LOCATION = "com.anda.moments.location";

    /**
     * Set this flag to GD_LOG_LEVEL_NONE when releasing your application in
     * order to remove all logs generated by GreenDroid.
     */
    private static final int GD_LOG_LEVEL = GD_LOG_LEVEL_NONE;

    /**
     * Indicates whether info logs are enabled. This should be true only when
     * developing/debugging an application/the library
     */
    public static final boolean GD_INFO_LOGS_ENABLED = (GD_LOG_LEVEL == GD_LOG_LEVEL_INFO);
    
    public static final String  IMAGELOADER_LOCAL_TITLE = "file://";
    
	/**
	 * 我的头像保存目录
	 */
	public static String MyAvatarDir = "/sdcard/com.anda.moments/head/";
	
	public static final String ACTION_MESSAGE_COUNT = "com.anda.moments.action.MESSAGE_COUNT";
	
	public static final int ACTION_CITY = 0x91;



    //tencent ads
    public static String TENCENT_ADS_APP_ID = "1105894034";
    public static String TENCENT_ADS_APP_WALL_ID = "";//app wall
    public static String InterteristalPosID = "2040519757175235";//插屏
    public static String SplashPosID = "2040718777873233";//开屏

//    public static final String InterteristalPosID = "8575134060152130849";
//    public static final String TENCENT_ADS_APP_ID = "1101152570";
//    public static final String SplashPosID = "8863364436303842593";
    
}